# Generated by Django 2.0.5 on 2018-09-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cozycorner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
