# Generated by Django 2.0.5 on 2018-09-13 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cozycorner', '0002_auto_20180912_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='img_url',
            field=models.CharField(max_length=200),
        ),
    ]
